export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const EDIT_EXPENDITURE = 'EDIT_EXPENDITURE';
export const EDIT_AVAILABLE_BAL = 'EDIT_AVAILABLE_BAL';