export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';

export const EDIT_BANK_CREDIT = 'EDIT_BANK_CREDIT';
export const EDIT_BANK_DEBIT = 'EDIT_BANK_DEBIT';
export const EDIT_BANK_BALANCE = 'EDIT_BANK_BALANCE';
export const EDIT_CASH_CREDIT = 'EDIT_CASH_CREDIT';
export const EDIT_CASH_DEBIT = 'EDIT_CASH_DEBIT';
export const EDIT_CASH_BALANCE = 'EDIT_CASH_BALANCE';

export const ADD_TRANSACTION_CATEGORY = 'ADD_TRANSACTION_CATEGORY';


