export const SET_CREDIT_DEBIT_ZERO = 'SET_CREDIT_DEBIT_ZERO';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const EDIT_TRANSACTION = 'EDIT_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';

export const EDIT_BANK_CREDIT = 'EDIT_BANK_CREDIT';
export const EDIT_BANK_DEBIT = 'EDIT_BANK_DEBIT';
export const EDIT_BANK_BALANCE = 'EDIT_BANK_BALANCE';
export const EDIT_CASH_CREDIT = 'EDIT_CASH_CREDIT';
export const EDIT_CASH_DEBIT = 'EDIT_CASH_DEBIT';
export const EDIT_CASH_BALANCE = 'EDIT_CASH_BALANCE';

export const GET_TRANSACTION_CATEGORIES = 'GET_TRANSACTION_CATEGORIES';
export const ADD_TRANSACTION_CATEGORY = 'ADD_TRANSACTION_CATEGORY';
export const DELETE_TRANSACTION_CATEGORY = 'DELETE_TRANSACTION_CATEGORY';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SET_USER_BANK_ACCOUNTS = 'SET_USER_BANK_ACCOUNTS';
export const SET_USER_PAYMENT_INSTRUMENTS = 'SET_USER_PAYMENT_INSTRUMENTS';
export const ADD_USER_PAYMENT_INSTRUMENT = 'ADD_USER_PAYMENT_INSTRUMENT';
export const SET_USER_CREDIT_CARDS = 'SET_USER_CREDIT_CARDS';
export const ADD_USER_BANK_ACCOUNT = 'ADD_USER_BANK_ACCOUNT';
export const ADD_USER_CREDIT_CARD = 'ADD_USER_CREDIT_CARD';
export const DELETE_USER_BANK_ACCOUNT = 'DELETE_USER_BANK_ACCOUNT';
