FROM node:16.13.2-alpine
WORKDIR /code
COPY ["package.json", "yarn.lock", "."]
RUN yarn --frozen-lockfile
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
RUN chown -R nextjs:nodejs apps/msite/.next
USER nextjs
EXPOSE 3000
ENV PORT 3000
RUN mkdir -p apps/backend
COPY ./apps/backend apps/backend
CMD ["yarn", "workspace", "@moneytracker/backend", "dev"]
